[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         docker
    Tag          docker.*

[OUTPUT]
    Name         stdout
    Match        docker.*

[OUTPUT]
    Name         loki
    Match        docker.*
    Host         172.18.0.6
    Port         3100
    Labels       job=fluentbit
    Label_keys   $container_name
