[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Tag               docker.<container_id>
    Tag_Regex         /var/lib/docker/containers/(?<container_id>[a-f0-9]{64})/
    Refresh_Interval  5
    Parser            docker
    Read_from_Head    False

[FILTER]
    Name    modify
    Match   docker.*
    Rename  log message

[FILTER]
    Name    lua
    Match   docker.*
    Script  /fluent-bit/etc/container_names.lua
    call    add_container_name

[OUTPUT]
    Name        loki
    Match       *
    Host        172.17.0.6
    Port        3100
    Labels      job=docker
    label_keys  $container_name,$stream
    line_format key_value
